In [177]:
import pandas as pd
from sklearn.datasets import load_iris
import numpy as np
from warnings import warn

iris = load_iris()

In [178]:
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [179]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [180]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [181]:
df = pd.DataFrame(iris.data, columns = iris.feature_names)
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [182]:
df['Flower'] = iris.target
df['Flower'] = df['Flower'].apply(lambda x: iris.target_names [x])
df

sepal length (cm)  sepal width (cm)  ...  petal width (cm)     Flower
0                  5.1               3.5  ...               0.2     setosa
1                  4.9               3.0  ...               0.2     setosa
2                  4.7               3.2  ...               0.2     setosa
3                  4.6               3.1  ...               0.2     setosa
4                  5.0               3.6  ...               0.2     setosa
..                 ...               ...  ...               ...        ...
145                6.7               3.0  ...               2.3  virginica
146                6.3               2.5  ...               1.9  virginica
147                6.5               3.0  ...               2.0  virginica
148                6.2               3.4  ...               2.3  virginica
149                5.9               3.0  ...               1.8  virginica

[150 rows x 5 columns]

In [183]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(iris.data, iris.target, test_size= 0.3, random_state= 20)


In [184]:
from sklearn.svm import SVC
model = SVC(kernel='rbf',C = 30, gamma= 'auto')
model.fit(X_train,y_train)

SVC(C=30, gamma='auto')

In [185]:
model.score(X_test,y_test)

0.8888888888888888

In [186]:
from sklearn.model_selection import cross_val_score

In [187]:
cross_val_score(SVC(kernel='linear',C=20, gamma='auto'),iris.data,iris.target, cv=5)

array([1.        , 1.        , 0.9       , 0.93333333, 1.        ])

In [188]:
cross_val_score(SVC(kernel='rbf',C=20, gamma='auto'),iris.data,iris.target, cv=5)

array([0.96666667, 1.        , 0.9       , 0.96666667, 1.        ])

In [189]:
cross_val_score(SVC(kernel='rbf',C=10, gamma='auto'),iris.data,iris.target, cv=5)

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [190]:
kernels = ['rbf','linear']
C = [1,10,20,30]

avg_score = {}
for kval in kernels:
    for cval in C:
        cv_score = cross_val_score(SVC(kernel=kval,C= cval, gamma='auto'),iris.data,iris.target, cv =5 )
        avg_score[kval +'_' + str(cval)] = np.average(cv_score)

avg_score

{'rbf_1': np.float64(0.9800000000000001),
 'rbf_10': np.float64(0.9800000000000001),
 'rbf_20': np.float64(0.9666666666666668),
 'rbf_30': np.float64(0.96),
 'linear_1': np.float64(0.9800000000000001),
 'linear_10': np.float64(0.9733333333333334),
 'linear_20': np.float64(0.9666666666666666),
 'linear_30': np.float64(0.96)}

In [191]:
from sklearn.model_selection import GridSearchCV

gsv = GridSearchCV(SVC(gamma='auto'),{
    'C': [1,10,20,30],
    'kernel': ['rbf', 'linear']
}, cv = 5, return_train_score= False)

gsv.fit(iris.data,iris.target)

GridSearchCV(cv=5, estimator=SVC(gamma='auto'),
             param_grid={'C': [1, 10, 20, 30], 'kernel': ['rbf', 'linear']})

In [192]:
gsv.cv_results_

{'mean_fit_time': array([0.00240912, 0.00241923, 0.00287738, 0.00188994, 0.00230355,
        0.00100627, 0.00150113, 0.00110302]),
 'std_fit_time': array([0.00039871, 0.00104413, 0.00094058, 0.00132459, 0.00104458,
        0.00063238, 0.00044614, 0.00037376]),
 'mean_score_time': array([0.00244651, 0.00275326, 0.00221982, 0.00109439, 0.00160246,
        0.00081124, 0.00095859, 0.00070295]),
 'std_score_time': array([1.23224914e-03, 1.24275371e-03, 1.50382097e-03, 9.49440619e-05,
        1.62905802e-03, 5.20667456e-04, 8.96184310e-04, 4.00445495e-04]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20, 30, 30],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear',
                    'rbf', 'linear'],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [

In [193]:
df = pd.DataFrame(gsv.cv_results_)
df

mean_fit_time  std_fit_time  ...  std_test_score  rank_test_score
0       0.002409      0.000399  ...        0.016330                1
1       0.002419      0.001044  ...        0.016330                1
2       0.002877      0.000941  ...        0.016330                1
3       0.001890      0.001325  ...        0.038873                4
4       0.002304      0.001045  ...        0.036515                5
5       0.001006      0.000632  ...        0.042164                6
6       0.001501      0.000446  ...        0.038873                7
7       0.001103      0.000374  ...        0.048990                7

[8 rows x 15 columns]

In [194]:
df[['param_C','param_kernel','mean_test_score']]

param_C param_kernel  mean_test_score
0        1          rbf         0.980000
1        1       linear         0.980000
2       10          rbf         0.980000
3       10       linear         0.973333
4       20          rbf         0.966667
5       20       linear         0.966667
6       30          rbf         0.960000
7       30       linear         0.960000

In [195]:
dir(gsv)

['__abstractmethods__',
 '__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_build_request_for_signature',
 '_check_feature_names',
 '_check_n_features',
 '_check_refit_for_multimetric',
 '_doc_link_module',
 '_doc_link_template',
 '_doc_link_url_param_generator',
 '_estimator_type',
 '_format_results',
 '_get_default_requests',
 '_get_doc_link',
 '_get_metadata_request',
 '_get_param_names',
 '_get_routed_params_for_fit',
 '_get_scorers',
 '_get_tags',
 '_more_tags',
 '_parameter_constraints',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_required_parameters',
 '_run

In [196]:
gsv.best_score_

np.float64(0.9800000000000001)

In [197]:
gsv.best_params_

{'C': 1, 'kernel': 'rbf'}

### RandomizedSearchCV

In [198]:
from sklearn.model_selection import RandomizedSearchCV

rsv = RandomizedSearchCV(SVC(gamma='auto'),{
    'C': [1,10,20,30],
    'kernel': ['rbf', 'linear']
}, cv = 5, return_train_score= False,n_iter=2)

rsv.fit(iris.data,iris.target)
pd.DataFrame(rsv.cv_results_)[['param_C','param_kernel','mean_test_score']]

param_C param_kernel  mean_test_score
0       20          rbf         0.966667
1       10       linear         0.973333

### Choosing the right model

In [199]:
from sklearn import svm
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

In [200]:
model_params = {
    'svm': {
        'model': svm.SVC(gamma='auto'),
        'params': {
            'C': [1, 10, 20],
            'kernel': ['rbf', 'linear']
        }
    },
    'random_forest': {
        'model': RandomForestClassifier(),
        'params': {
            'n_estimators': [1, 5, 10]
        }
    },
    'logistic_regression': {
        'model': LogisticRegression(solver='liblinear', multi_class='auto'),
        'params': {
            'C': [1, 5, 10]
        }
    }
}

In [201]:
# Initialize a list to store results
scores = []

# Loop through each model and its parameters
for model_name, mp in model_params.items():
    # Set up GridSearchCV
    clf = GridSearchCV(mp['model'],mp['params'], cv = 5,return_train_score=False)
    # Fit the model
    clf.fit(iris.data,iris.target)
    
    # Store results
    scores.append( {
        'model':model_name, 
        'best_score': clf.best_score_,
        'best_params':clf.best_params_
    })



C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\numpy\ma\core.py:2881: RuntimeWarning: invalid value encountered in cast
  _data = np.array(data, dtype=dtype, copy=copy,
C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid th

In [202]:
dff = pd.DataFrame(scores, columns=['model','best_score','best_params'])
dff

model  best_score                best_params
0                  svm    0.980000  {'C': 1, 'kernel': 'rbf'}
1        random_forest    0.960000       {'n_estimators': 10}
2  logistic_regression    0.966667                   {'C': 5}