In [22]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits

digits = load_digits()

In [23]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(digits.data,digits.target, test_size=0.3)

In [24]:
lr = LogisticRegression()
lr.fit(X_train,y_train)


C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [25]:
lr.score(X_test,y_test)

0.9592592592592593

In [ ]:
svm= SVC(kernel='rbf',C = 30, gamma= 'auto')
svm.fit(X_train,y_train)

SVC(C=30, gamma='auto')

In [27]:
svm.score(X_test,y_test)

0.3888888888888889

In [28]:
rf = RandomForestClassifier()
rf.fit(X_train,y_train)

RandomForestClassifier()

In [29]:
rf.score(X_test,y_test)

0.9685185185185186

In [30]:
from sklearn.model_selection import KFold
kf = KFold (n_splits= 3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [31]:
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [ ]:
def get_score(model, X_train,X_test,y_train,y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [34]:
get_score(LogisticRegression(),X_train,X_test,y_train,y_test)

C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9592592592592593

In [37]:
from sklearn.model_selection import StratifiedGroupKFold
folds = StratifiedGroupKFold(n_splits=3)

In [59]:
score_L = []
scores_svm = []
score_rf = []
for train_index, test_index in kf.split(digits.data):
    X_train,X_test,y_train,y_test = digits.data[train_index], digits.data[test_index],digits.target[train_index],digits.target[test_index]
    score_L.append(get_score(LogisticRegression(n_jobs=20),X_train,X_test,y_train,y_test))
    scores_svm.append(get_score(SVC(kernel='rbf',C = 30, gamma= 'auto'),X_train,X_test,y_train,y_test))
    score_rf.append(get_score(RandomForestClassifier(n_estimators= 40),X_train,X_test,y_train,y_test))


In [60]:
score_L

[0.9232053422370617, 0.9415692821368948, 0.9148580968280468]

In [61]:
score_rf

[0.9398998330550918, 0.9398998330550918, 0.9265442404006677]

In [62]:
scores_svm

[0.4307178631051753, 0.44407345575959933, 0.46243739565943237]

In [ ]:
#Shorter way of doing it
from sklearn.model_selection import cross_val_score

In [65]:
cross_val_score(LogisticRegression(), digits.data,digits.target)

C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stab

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [68]:
cross_val_score(SVC(kernel = 'rbf',C =30, gamma='auto'), digits.data,digits.target)

array([0.45277778, 0.46944444, 0.47910864, 0.47910864, 0.50139276])

In [70]:
cross_val_score(RandomForestClassifier(n_estimators= 40), digits.data,digits.target)

array([0.91944444, 0.91666667, 0.95543175, 0.96100279, 0.90529248])

In [71]:
cross_val_score(RandomForestClassifier(n_estimators= 5), digits.data,digits.target)

array([0.84722222, 0.79722222, 0.87465181, 0.90807799, 0.8356546 ])

In [72]:
cross_val_score(RandomForestClassifier(n_estimators= 20), digits.data,digits.target)

array([0.925     , 0.89722222, 0.95264624, 0.94986072, 0.89972145])

In [73]:
cross_val_score(RandomForestClassifier(n_estimators= 50), digits.data,digits.target)

array([0.93055556, 0.93055556, 0.94707521, 0.95264624, 0.91364903])